export const GRAPH_DATA_REQUEST = 'GRAPH_DATA_REQUEST';
export const GRAPH_DATA_SUCCESS = 'GRAPH_DATA_SUCCESS';
export const GRAPH_DATA_FAIL = 'GRAPH_DATA_FAIL';

export const SHOW_PREVIEW_PANEL = 'SHOW_PREVIEW_PANEL';
export const HIDE_PREVIEW_PANEL = 'HIDE_PREVIEW_PANEL';
export const EXTEND_PREVIEW_PANEL = 'EXTEND_PREVIEW_PANEL';

export const PREVIEW_REQUEST = 'PREVIEW_REQUEST';
export const PREVIEW_SUCCESS = 'PREVIEW_SUCCESS';
export const PREVIEW_FAIL = 'PREVIEW_FAIL';
