export const AUTHOR_REQUEST = 'AUTHOR_REQUEST';
export const AUTHOR_SUCCESS = 'AUTHOR_SUCCESS';
export const AUTHOR_FAIL = 'AUTHOR_FAIL';

export const SHOW_AUTHOR_PANEL = 'SHOW_AUTHOR_PANEL';
export const HIDE_AUTHOR_PANEL = 'HIDE_AUTHOR_PANEL';
