export const ARTICLES_REQUEST = 'ARTICLES_REQUEST';
export const ARTICLES_SUCCESS = 'ARTICLES_SUCCESS';
export const ARTICLES_FAIL = 'ARTICLES_FAIL';

export const FILTER_ARTICLES_TITLE = 'FILTER_ARTICLES_TITLE';
export const FILTER_ARTICLES_CATEGORY = 'FILTER_ARTICLES_CATEGORY';
// export const FILTER_ARTICLES_LANGUAGE = 'FILTER_ARTICLES_LANGUAGE';
export const EMPTY_ARTICLES_FILTER = 'EMPTY_ARTICLES_FILTER';
