export const CATEGORIES_REQUEST = 'CATEGORIES_REQUEST';
export const CATEGORIES_SUCCESS = 'CATEGORIES_SUCCESS';
export const CATEGORIES_FAIL = 'CATEGORIES_FAIL';

export const SET_LANGUAGE_FR = 'SET_LANGUAGE_FR';
export const SET_LANGUAGE_EN = 'SET_LANGUAGE_EN';
