export const SHOW_TITLEBAR = 'SHOW_TITLEBAR';
export const HIDE_TITLEBAR = 'HIDE_TITLEBAR';
export const SET_ARTICLE_TITLEBAR = 'SET_ARTICLE_TITLEBAR';
export const SET_STD_TITLEBAR = 'SET_STD_TITLEBAR';
export const EMPTY_TITLEBAR = 'EMPTY_TITLEBAR';
