export const SHOW_PREVIEW_PANEL = 'SHOW_PREVIEW_PANEL';
export const HIDE_PREVIEW_PANEL = 'HIDE_PREVIEW_PANEL';
export const EXTEND_PREVIEW_PANEL = 'EXTEND_PREVIEW_PANEL';
export const HIDE_EXTENDED_PREVIEW_PANEL = 'HIDE_EXTENDED_PREVIEW_PANEL';

export const PREVIEW_REQUEST = 'PREVIEW_REQUEST';
export const PREVIEW_SUCCESS = 'PREVIEW_SUCCESS';
export const PREVIEW_FAIL = 'PREVIEW_FAIL';
