export const SET_THEME_BLUE = 'SET_THEME_BLUE';
export const SET_THEME_WHITE = 'SET_THEME_WHITE';

export const SHOW_MENU = 'SHOW_MENU';
export const HIDE_MENU = 'HIDE_MENU';

export const SHOW_TITLEBAR = 'SHOW_TITLEBAR';
export const HIDE_TITLEBAR = 'HIDE_TITLEBAR';
export const SET_TITLEBAR = 'SET_TITLEBAR';

export const NEWS_REQUEST = 'NEWS_REQUEST';
export const NEWS_SUCCESS = 'NEWS_SUCCESS';
export const NEWS_FAIL = 'NEWS_FAIL';

export const ARTICLE_REQUEST = 'ARTICLE_REQUEST';
export const ARTICLE_SUCCESS = 'ARTICLE_SUCCESS';
export const ARTICLE_FAIL = 'ARTICLE_FAIL';

export const SET_PERCENT_READ = 'SET_PERCENT_READ';

export const AUTHOR_REQUEST = 'AUTHOR_REQUEST';
export const AUTHOR_SUCCESS = 'AUTHOR_SUCCESS';
export const AUTHOR_FAIL = 'AUTHOR_FAIL';

export const SHOW_AUTHOR_PANEL = 'SHOW_AUTHOR_PANEL';
export const HIDE_AUTHOR_PANEL = 'HIDE_AUTHOR_PANEL';

export const AUTHOR_ARTICLES_REQUEST = 'AUTHOR_ARTICLES_REQUEST';
export const AUTHOR_ARTICLES_SUCCESS = 'AUTHOR_ARTICLES_SUCCESS';
export const AUTHOR_ARTICLES_FAIL = 'AUTHOR_ARTICLES_FAIL';
