export const AUTHORS_REQUEST = 'AUTHORS_REQUEST';
export const AUTHORS_SUCCESS = 'AUTHORS_SUCCESS';
export const AUTHORS_FAIL = 'AUTHORS_FAIL';

export const FILTER_AUTHORS_NAME = 'FILTER_AUTHORS_NAME';
export const FILTER_AUTHORS_CATEGORY = 'FILTER_AUTHORS_CATEGORY';
export const EMPTY_AUTHORS_FILTER = 'EMPTY_AUTHORS_FILTER';
